services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: message_integration_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-message_integration}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-message_integration}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço da Aplicação
  app:
    build: .
    container_name: message_integration_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Sobrescreve a DATABASE_URL para apontar para o container 'db' em vez de 'localhost'
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-mysecretpassword}@db:5432/${DB_NAME:-message_integration}
    env_file:
      # Carrega as variáveis de credenciais do arquivo .env local (Yampi tokens, etc.)
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs_from_container:/app/logs
      - ./src:/app/src
      - ./emails_from_container:/app/emails

volumes:
  pgdata:
